name: customer-io
synopsis: customer.io library
spec-version: 0.36.0
maintainer: Bitnomial <support@bitnomial.com>
homepage: https://customer.io
author: Bitnomial
copyright: 2025 Bitnomial, Inc.
license: AllRightsReserved
version: 0.1.0

language: GHC2021

library:
  source-dirs: src/lib
  ghc-options:
    - -Wall
    - -Werror
    - -Wmissing-home-modules
    - -Widentities
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wmissing-export-lists
    - -Wno-unused-do-bind
    - -Wunused-packages
    - -funbox-strict-fields
    - -fwrite-ide-info
  dependencies:
    - base
    - aeson
    - containers
    - http-client
    - http-client-tls
    - mtl
    - servant
    - servant-client
    - text
